package com.woolab.lumella

import com.woolab.lumella.contract.CoachIndicator

/**
 * Maps a [CoachIndicator] to the honest per-turn display line for the bottom hint
 * (08/05 requirement 3): `음성 LLM-GPT · 코치 <label>(<한국어 라우트>) · <기존 힌트>`.
 *
 * Why the voice segment is a hardcoded literal, never derived from [CoachIndicator]:
 * the audible VOICE the learner hears is always generated by the realtime LLM
 * ([com.woolab.lumella.voice.OpenAiRealtimeTransport]) — that never changes turn to
 * turn. [CoachIndicator] instead describes luma's SLOW path: which route/provider
 * (e.g. ETRI TANGO) produced the steering evidence used to coach the *next* turn.
 * Those are two different models serving two different roles. Rendering only the
 * coach segment — e.g. "코치 SLM-TANGO" with no voice segment at all — would read to
 * the learner as "the voice is TANGO", which is false; this exact dishonesty risk is
 * called out in the 08/05 feasibility verdict (`docs/requirements-feasibility.md`).
 * So [hintLine] always prefixes the fixed "음성 LLM-GPT" whenever it shows a coach
 * segment, structurally preventing that misreading rather than relying on wording.
 */
object CoachIndicatorLabel {

    private const val VOICE_SEGMENT = "음성 LLM-GPT"

    private val PROVIDER_LABELS = mapOf(
        "etri" to "SLM-TANGO",
        "openai" to "LLM-GPT",
        // luma's provider Literal permits a third value; without this a learner would see
        // "코치 INTERNAL(…)". No SLM/LLM prefix on purpose — the internal engine is neither.
        "internal" to "내부",
    )

    private val ROUTE_NAMES = mapOf(
        "free_chat" to "자유대화",
        "reading" to "읽기",
        "scenario" to "상황극",
        "gpt_qa" to "질문답변",
        "image_talk" to "사진대화",
        "topic_chat" to "주제대화",
        "writing_handoff" to "쓰기",
        "fallback_tutor" to "기본",
        // Not routable yet — the ETRI ASE endpoint does not exist on our server. The label
        // is pre-wired so that when luma gains the route, the glasses need no change.
        "speaking_eval" to "말하기평가",
    )

    /**
     * Collapses anything that would break the one-physical-line hint bar — newlines, tabs,
     * NUL, escape — into single spaces. Today's wire schema is a closed enum so this is
     * unreachable, but nothing between the wire and this mapper validates shape, and a
     * later free-text field would otherwise turn the hint bar into a multi-line surprise.
     */
    private fun oneLine(value: String): String =
        value.map {
            // U+2028/2029 break lines without being ISO control characters.
            if (it.isISOControl() || it == '\u2028' || it == '\u2029') ' ' else it
        }.joinToString("").trim()

    /** Display label for a wire `provider` value. Unknown providers fall back to the uppercased raw value. */
    fun providerLabel(provider: String): String =
        PROVIDER_LABELS[provider] ?: oneLine(provider).uppercase()

    /** Korean display name for a wire `route` value. Unknown routes fall back to the raw value. */
    fun routeName(route: String): String =
        ROUTE_NAMES[route] ?: oneLine(route)

    /**
     * Builds the full bottom-hint line.
     *
     * @param indicator `null` when no coach routing data is available (nothing honest to
     *   show yet, e.g. before the first turn or when luma is unreachable) — [baseHint] is
     *   returned unchanged. When present, the indicator is prefixed onto [baseHint]; see
     *   the class KDoc for why the voice segment is a hardcoded literal.
     */
    fun hintLine(indicator: CoachIndicator?, baseHint: String): String {
        if (indicator == null) return baseHint
        return "$VOICE_SEGMENT · ${coachSegment(indicator)} · $baseHint"
    }

    /**
     * The transient variant shown right after a turn's routing arrives: the coach segment
     * plus the router's own stated REASON, replacing the base hint for a few seconds before
     * [hintLine] takes back over. The reason is width-budgeted (Hangul counts double, the
     * ellipsis costs one) because requirement 1 of the same memo is about NOT covering the
     * wearer's view — a two-line hint is the ceiling, never three.
     */
    fun hintLineWithReason(indicator: CoachIndicator, baseHint: String): String {
        val reason = indicator.reason?.takeIf { it.isNotBlank() }
            ?: return hintLine(indicator, baseHint)
        return "$VOICE_SEGMENT · ${coachSegment(indicator)} · 사유: ${clipToWidth(oneLine(reason), REASON_WIDTH_BUDGET)}"
    }

    private fun coachSegment(indicator: CoachIndicator): String {
        // Dr. Hwang's memo names this exact label. A speaking-eval turn served by ETRI is
        // the ASE engine, not TANGO — same provider string, different service.
        val label = if (indicator.route == "speaking_eval" && indicator.provider == "etri") {
            "SLM-ASE"
        } else {
            providerLabel(indicator.provider)
        }
        val route = routeName(indicator.route)
        val confidence = indicator.confidencePercent?.let { " ${it}%" } ?: ""
        // 시도→최종: a repaired turn shows the engine that tried first, so TANGO's
        // participation is visible instead of silently absorbed by the repair.
        val attempted = indicator.attemptedProvider
            ?.takeIf { it != indicator.provider }
            ?.let { "${providerLabel(it)}→" } ?: ""
        return "코치 $attempted$label($route$confidence)"
    }

    /** Display-width clip: wide (Hangul-class) chars cost 2 units, the ellipsis costs 1. */
    private fun clipToWidth(value: String, budget: Int): String {
        var width = 0
        val sb = StringBuilder()
        for (ch in value) {
            val w = if (ch.code >= 0x1100) 2 else 1
            if (width + w > budget - 1) return sb.append("…").toString()
            sb.append(ch)
            width += w
        }
        return sb.toString()
    }

    /**
     * ~90 Latin units ≈ 45 Hangul chars. The first budget (40) clipped almost every real
     * reason — the router writes full sentences. The hint view caps at three lines
     * (maxLines in the layout is the hard backstop), and the fixed segments plus 90 units
     * fit inside that.
     */
    private const val REASON_WIDTH_BUDGET = 90
}
