package com.woolab.lumella

import com.woolab.lumella.contract.CoachIndicator

/**
 * Maps a [CoachIndicator] to the honest per-turn display line for the bottom hint
 * (08/05 requirement 3): `음성 LLM-GPT · 코치 <label>(<한국어 라우트>) · <기존 힌트>`.
 *
 * Why the voice segment is a hardcoded literal, never derived from [CoachIndicator]:
 * the audible VOICE the learner hears is always generated by the realtime LLM
 * ([com.woolab.lumella.voice.OpenAiRealtimeTransport]) — that never changes turn to
 * turn. [CoachIndicator] instead describes luma's SLOW path: which route/provider
 * (e.g. ETRI TANGO) produced the steering evidence used to coach the *next* turn.
 * Those are two different models serving two different roles. Rendering only the
 * coach segment — e.g. "코치 SLM-TANGO" with no voice segment at all — would read to
 * the learner as "the voice is TANGO", which is false; this exact dishonesty risk is
 * called out in the 08/05 feasibility verdict (`docs/requirements-feasibility.md`).
 * So [hintLine] always prefixes the fixed "음성 LLM-GPT" whenever it shows a coach
 * segment, structurally preventing that misreading rather than relying on wording.
 */
object CoachIndicatorLabel {

    private const val VOICE_SEGMENT = "음성 LLM-GPT"

    private val PROVIDER_LABELS = mapOf(
        "etri" to "SLM-TANGO",
        "openai" to "LLM-GPT",
    )

    private val ROUTE_NAMES = mapOf(
        "free_chat" to "자유대화",
        "reading" to "읽기",
        "scenario" to "상황극",
        "gpt_qa" to "질문답변",
        "image_talk" to "사진대화",
        "topic_chat" to "주제대화",
        "writing_handoff" to "쓰기",
        "fallback_tutor" to "기본",
    )

    /** Display label for a wire `provider` value. Unknown providers fall back to the uppercased raw value. Never empty. */
    fun providerLabel(provider: String): String =
        PROVIDER_LABELS[provider] ?: provider.uppercase()

    /** Korean display name for a wire `route` value. Unknown routes fall back to the raw value. Never empty. */
    fun routeName(route: String): String =
        ROUTE_NAMES[route] ?: route

    /**
     * Builds the full bottom-hint line.
     *
     * @param indicator `null` when no coach routing data is available (nothing honest to
     *   show yet, e.g. before the first turn or when luma is unreachable) — [baseHint] is
     *   returned unchanged. When present, the indicator is prefixed onto [baseHint]; see
     *   the class KDoc for why the voice segment is a hardcoded literal.
     */
    fun hintLine(indicator: CoachIndicator?, baseHint: String): String {
        if (indicator == null) return baseHint
        val label = providerLabel(indicator.provider)
        val route = routeName(indicator.route)
        return "$VOICE_SEGMENT · 코치 $label($route) · $baseHint"
    }
}
